version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password | docker login --username AWS --password-stdin 112567001577.dkr.ecr.us-east-2.amazonaws.com/fleet-manager-application-respository
      - REPOSITORY_URI=112567001577.dkr.ecr.us-east-2.amazonaws.com/fleet-manager-application-respository
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f DockerfilePreProd -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"container-fleet-manager-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > image-definition.json
artifacts:
  files:
    - image-definition.json
