

describe(" ACE eManifest e2e Test cases", () => {
  /* === Test Created with Cypress Studio === */
  it.only('Add ACE test ', function () {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('http://localhost:4200/');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('e2etestcarrier');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('FleetHawks@2502');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(3) > .nav-link').click();
    cy.get(':nth-child(5) > .nav-link > span').click();
    cy.get('.page-header > .form-horizontal > .row > .text-right > .btn').click();
    cy.get('.col-lg-3 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').click();
    cy.get('.offset-lg-1 > .row > .col-lg-7 > .form-control').clear();
    cy.get('.offset-lg-1 > .row > .col-lg-7 > .form-control').type('CYPRESS104');
    cy.get('#form_ > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').click();
    cy.get('.offset-lg-1 > .row > :nth-child(4) > .form-control').click();
    cy.get('[aria-label="Select month"]').select('5');
    cy.get('[aria-label="Monday, May 31, 2021"] > .btn-light').click();
    cy.get('.offset-lg-1 > .row > :nth-child(5) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) > div:nth-of-type(33)').click();
    cy.get('#form_ > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(4) > .ng-option-label.ng-star-inserted').click();
    cy.get('#form_ > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(1) > .form-control').clear();
    cy.get('#form_ > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(1) > .form-control').type('4');
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(2) > .form-control').clear();
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(2) > .form-control').type('6');
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(3) > .form-control').clear();
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(3) > .form-control').type('8');
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(4) > .form-control').clear();
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(3) > .row > :nth-child(4) > .form-control').type('6');
    cy.get('#form_ > :nth-child(1) > :nth-child(3) > :nth-child(1) > :nth-child(4) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').click();
    cy.get('#mainDriver > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').click();
    cy.get(':nth-child(1) > :nth-child(3) > :nth-child(2) > :nth-child(2) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[role="option"]:nth-of-type(1) .ng-star-inserted ').click();
    cy.get('#form_ > :nth-child(2) > .text-right > .btn').click();
    cy.get('input[name="passengers[0].firstName"]').clear();
    cy.get('input[name="passengers[0].firstName"]').type('William');
    cy.get(':nth-child(1) > :nth-child(3) > .form-group > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(1) > :nth-child(3) > .form-group > :nth-child(1) > .form-control').type('Johns');
    cy.get('.form-group > :nth-child(2) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('.col > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(37)').click();
    cy.get('.row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').clear();
    cy.get('.row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').type('567891234');
    cy.get('.row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(2) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(12)').click();
    cy.get(':nth-child(1) > :nth-child(3) > .form-group > :nth-child(2) > .form-control').click();
    cy.get('[aria-label="Select month"]').select('1');
    cy.get('[aria-label="Select year"]').select('1995');
    cy.get('[tabindex="0"] > .btn-light').click();
    cy.get(':nth-child(3) > .form-group > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label=" Birth Certificate"]').click();
    cy.get('#passengerDocStateSelect > .ng-select-container').click();
    cy.get('div[role="option"]').click();
    cy.get('#addDocBtn').click();
    cy.get(':nth-child(3) > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(3) > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').type('424868801');
    cy.get(':nth-child(3) > .offset-lg-1 > .form-group > :nth-child(2) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(36)').click();
    cy.get(':nth-child(3) > :nth-child(3) > .form-group > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label=" Driver\'s License"]').click();
    cy.get(':nth-child(3) > :nth-child(3) > .form-group > :nth-child(2) > #passengerDocStateSelect > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label="NB - New Brunswick"]').click();
    cy.get('.col > .btn').click();
    cy.get(':nth-child(4) > .col > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(4) > .col > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').type('Caroline');
    cy.get(':nth-child(4) > .col > :nth-child(1) > :nth-child(3) > .form-group > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(4) > .col > :nth-child(1) > :nth-child(3) > .form-group > :nth-child(1) > .form-control').type('Forbes');
    cy.get(':nth-child(4) > .col > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get(':nth-child(4) > .col > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label=" United States"]').click();
    cy.get(':nth-child(4) > .col > .row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(4) > .col > .row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(1) > .form-control').type('543216789');
    cy.get(':nth-child(4) > .col > .row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(2) > .ng-select > .ng-select-container').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(36)').click();
    //cy.get(':nth-child(4) > .col > .row.ng-star-inserted > .offset-lg-1 > .form-group > :nth-child(2) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    //cy.get('div:nth-of-type(6) > .ng-option-label.ng-star-inserted').click();
    cy.get(':nth-child(4) > .col > :nth-child(1) > :nth-child(3) > .form-group > :nth-child(2) > .form-control').click();
    cy.get('[aria-label="Select year"]').select('1998');
    cy.get('[aria-label="Thursday, April 30, 1998"] > .btn-light').click();
    cy.get(':nth-child(4) > .col > .row.ng-star-inserted > :nth-child(3) > .form-group > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(6) > .ng-option-label.ng-star-inserted').click();
    cy.get(':nth-child(4) > .col > .row.ng-star-inserted > :nth-child(3) > .form-group > :nth-child(2) > #passengerDocStateSelect > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(5)').click();

    // shipment 1
    cy.get('.mat-expansion-panel').click();
    cy.get('#cdk-accordion-child-0 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').last().click();
    cy.get('#cdk-accordion-child-0 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-4 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('.ng-dropdown-panel-items [ng-reflect-ng-item-label="DOTL"]').last().click();
    cy.get('.col-lg-8 > .form-control').clear();
    cy.get('.col-lg-8 > .form-control').type('TEST1233');
    cy.get('#cdk-accordion-child-0 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get(' div:nth-of-type(2) [role="option"]:nth-of-type(7)').last().click();
    cy.get('#cdk-accordion-child-0 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get(' div:nth-of-type(2) [role="option"]:nth-of-type(2)').last().click();
    cy.get('#cdk-accordion-child-0 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('.ng-dropdown-panel-items [ng-reflect-ng-item-label=" fleet hawks pvt "]').last().click();
    cy.get('.mat-expansion-panel-body > :nth-child(3) > .col-lg-5.offset-lg-1 > .row > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('.ng-dropdown-panel-items [ng-reflect-ng-item-label=" Affiliated Company"]').click();
    cy.get(':nth-child(3) > :nth-child(3) > .row > .col-lg-10 > .form-control').clear();
    cy.get(':nth-child(3) > :nth-child(3) > .row > .col-lg-10 > .form-control').type('Damon Salvotore');
    cy.get(':nth-child(6) > .offset-lg-1 > :nth-child(1) > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get(':nth-child(6) > .offset-lg-1 > :nth-child(1) > .col-lg-10.ng-star-inserted > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div[role="option"]').click();
    cy.get(':nth-child(2) > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(12)').click();
    cy.get('.offset-lg-1 > :nth-child(3) > :nth-child(1) > .form-control').clear();
    cy.get('.offset-lg-1 > :nth-child(3) > :nth-child(1) > .form-control').type('truck')
    cy.get(':nth-child(2) > .row > .col-lg-5 > .form-control').clear();
    cy.get(':nth-child(2) > .row > .col-lg-5 > .form-control').type('5');
    cy.get(':nth-child(3) > :nth-child(2) > .row > .col-lg-7 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(7)').click();
    cy.get(':nth-child(3) > .row > .col-lg-5 > .form-control').clear();
    cy.get(':nth-child(3) > .row > .col-lg-5 > .form-control').type('200');
    cy.get(':nth-child(3) > :nth-child(3) > .row > .col-lg-7 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('.ng-dropdown-panel-items [ng-reflect-ng-item-label="Kilograms"]').click();

    //shipment 2

    cy.get(':nth-child(8) > .col-lg-12 > .btn').click();
    cy.get('#mat-expansion-panel-header-1 > .mat-content > .mat-expansion-panel-header-title').click();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').last().click();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-4 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').last().click();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-8 > .form-control').clear();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-8 > .form-control').type('TEST9914');
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(6)').last().click();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('[ng-reflect-ng-item-label=" 61 Immediate Transportation"]').last().click();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').last().click();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(4) > .form-control').clear();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(4) > .form-control').type('546862410');
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(5) > .form-control').clear();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(5) > .form-control').type('678954321');
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(2) > .form-control').clear();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(2) > .form-control').type('751234678');
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(6) > .form-control').click();
    cy.get('[aria-label="Select month"]').select('5');
    cy.get('[aria-label="Monday, May 31, 2021"] > .btn-light').click();
    cy.get('.col-lg-10.ng-star-inserted > .row > :nth-child(7) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label="YES"]').click();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').last().click();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1) ').first().click();

    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(1) > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').last().click();
    cy.get('#cdk-accordion-child-1 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(1) > .col-lg-10.ng-star-inserted > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div[role="option"]').click();
    cy.get(':nth-child(3) > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(6)').click();
    cy.get('.offset-lg-1 > :nth-child(4) > :nth-child(1) > .form-control').clear();
    cy.get('.offset-lg-1 > :nth-child(4) > :nth-child(1) > .form-control').type('Box truck');
    cy.get(':nth-child(4) > :nth-child(2) > .row > .col-lg-5 > .form-control').clear();
    cy.get(':nth-child(4) > :nth-child(2) > .row > .col-lg-5 > .form-control').type('5');
    cy.get(':nth-child(4) > :nth-child(2) > .row > .col-lg-7 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(7)').click();
    cy.get(':nth-child(4) > :nth-child(3) > .row > .col-lg-5 > .form-control').clear();
    cy.get(':nth-child(4) > :nth-child(3) > .row > .col-lg-5 > .form-control').type('200');
    cy.get(':nth-child(4) > :nth-child(3) > .row > .col-lg-7 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('.ng-dropdown-panel-items [ng-reflect-ng-item-label="Kilograms"]').click();

    // shipment 3
    cy.get(':nth-child(8) > .col-lg-12 > .btn').click();
    cy.get('#mat-expansion-panel-header-2 > .mat-content > .mat-expansion-panel-header-title').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label=" Goods Astray"]').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-4 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-8 > .form-control').clear();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(2) > .row > .col-lg-8 > .form-control').type('TEST5555');
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > .offset-lg-1 > .form-group > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(5)').click();
    cy.get('.col-lg-10.ng-star-inserted > .form-control').click();
    cy.get('[aria-label="Select month"]').select('5');
    cy.get('[aria-label="Monday, May 31, 2021"] > .btn-light').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();

    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(1) > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(1) > .col-lg-10.ng-star-inserted > .ng-select > .ng-select-container').click();
    cy.get('div[role="option"]').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(2) > .col-lg-10 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(12)').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(1) > .form-control').clear();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(1) > .form-control').type('Van');
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(2) > .row > .col-lg-5 > .form-control').clear();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(2) > .row > .col-lg-5 > .form-control').type('4');
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(2) > .row > .col-lg-7 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(7)').click();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(3) > .row > .col-lg-5 > .form-control').clear();
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(3) > .row > .col-lg-5 > .form-control').type('500');
    cy.get('#cdk-accordion-child-2 > .mat-expansion-panel-body > .form-group.ng-star-inserted > .offset-lg-1 > :nth-child(3) > :nth-child(3) > .row > .col-lg-7 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('.ng-dropdown-panel-items [ng-reflect-ng-item-label="Kilograms"]').click();

    cy.get('tr.ng-star-inserted > :nth-child(1) > .row > .col-lg-12 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('tr.ng-star-inserted > :nth-child(2) > .row > .col-lg-12 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label=" Gondola \(Closed\)"]').click();
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(1) > .form-control').clear();
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(1) > .form-control').type('2');
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(2) > .form-control').clear();
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(2) > .form-control').type('4');
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(3) > .form-control').clear();
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(3) > .form-control').type('6');
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(4) > .form-control').clear();
    cy.get('.mr-1 > .col-lg-12 > .row > :nth-child(4) > .form-control').type('9');
    cy.get('tr.ng-star-inserted > :nth-child(4) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(1) > .ng-option-label.ng-star-inserted').click();

    // cy.get(':nth-child(9) > .text-right > .btn').click();
    // cy.get('tbody > :nth-child(2) > :nth-child(1) > .row > .col-lg-12 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    // cy.get('tbody > :nth-child(2) > :nth-child(2) > .row > .col-lg-12 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    // cy.get('[ng-reflect-ng-item-label=" Gondola \(Closed\)"]').last().click();
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(1) > .form-control').clear();
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(1) > .form-control').type('9');
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(2) > .form-control').clear();
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(2) > .form-control').type('9');
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(3) > .form-control').clear();
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(3) > .form-control').type('1');
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(4) > .form-control').clear();
    // cy.get(':nth-child(2) > :nth-child(3) > .mr-1 > .col-lg-12 > .row > :nth-child(4) > .form-control').type('4');

    cy.get('#form_ > .mt-3 > .col-lg-12 > .btn-success').click();
    /* ==== End Cypress Studio ==== */
  });
  /* === Test Created with Cypress Studio === */
  it('Search-Reset of ACE eManifest', function () {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('http://localhost:4200/');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('e2etestcarrier');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('FleetHawks@2502');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(3) > .nav-link').click();
    cy.get(':nth-child(5) > .nav-link > span').click();
    cy.get('.page-header > .form-horizontal > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('.form-horizontal > .row > .pr-0 > .ng-select > .ng-select-container').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('[name="fromDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(2) [role="gridcell"]:nth-of-type(6) [ng-reflect-current-month]').click();
    cy.get('input[name="toDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(7) [role="gridcell"]:nth-of-type(1) [ng-reflect-current-month]').click();
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get(':nth-child(4) > [type="button"]').click();
    cy.get('.page-header > .form-horizontal > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get('.pr-0 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').clear();
    cy.get('.pr-0 > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').type('tesla x');
    cy.get('div[role="option"]').click();
    cy.get('[name="fromDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(2) [role="gridcell"]:nth-of-type(6) [ng-reflect-current-month]').click();
    cy.get('input[name="toDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(7) [role="gridcell"]:nth-of-type(1) [ng-reflect-current-month]').click();
    cy.get(':nth-child(4) > .mr-2').click();
    //cy.get('[name="toDate"]').click();
    //cy.get('[aria-label="Thursday, April 29, 2021"] > .btn-light').click();
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get(':nth-child(4) > [type="button"]').click();
    cy.get('.page-header > .form-horizontal > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(3) > .ng-option-label').click();
    cy.get('.pr-0 > .input-group > .form-control').clear();
    cy.get('.pr-0 > .input-group > .form-control').type('0101');
    cy.get('[name="fromDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(2) [role="gridcell"]:nth-of-type(6) [ng-reflect-current-month]').click();
    cy.get('input[name="toDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(7) [role="gridcell"]:nth-of-type(1) [ng-reflect-current-month]').click();
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get('.pr-0 > .input-group > .form-control').clear();
    cy.get('.pr-0 > .input-group > .form-control').type('0102');
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get('.pr-0 > .input-group > .form-control').clear();
    cy.get('.pr-0 > .input-group > .form-control').type('0103');
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get(':nth-child(4) > [type="button"]').click();
    cy.get('.page-header > .form-horizontal > .row > :nth-child(1) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[ng-reflect-ng-item-label=" Trip Number"]').click();
    cy.get('.pr-0 > .input-group > .form-control').clear();
    cy.get('.pr-0 > .input-group > .form-control').type('DOTLTEST0002');
    cy.get('[name="fromDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(2) [role="gridcell"]:nth-of-type(6) [ng-reflect-current-month]').click();
    cy.get('input[name="toDate"]').click();
    cy.get('[role] [role="row"]:nth-of-type(7) [role="gridcell"]:nth-of-type(1) [ng-reflect-current-month]').click();
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get('.pr-0 > .input-group > .form-control').clear();
    cy.get('.pr-0 > .input-group > .form-control').type('DOTLTEST0007');
    cy.get(':nth-child(4) > .mr-2').click();
    cy.get(':nth-child(4) > [type="button"]').click();
    /* ==== End Cypress Studio ==== */
  });
  /* === Test Created with Cypress Studio === */
  it('detailing', function () {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('http://localhost:4200/');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('e2etestcarrier');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('FleetHawks@2502');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(3) > .nav-link').click();
    cy.get(':nth-child(5) > .nav-link > .fas').click();
    cy.get('#ace > tbody > :nth-child(1) > :nth-child(1)').click();
    cy.get('#ace .ng-star-inserted:nth-of-type(1) [tabindex="0"]:nth-of-type(1)').click();
    cy.get('.btn.btn-sm.btn-success.dropdown-toggle').click();
    cy.get('.btn-group.btn-group1.flex-wrap.mr-1.show > div[role="menu"] > a:nth-of-type(2)').click();
    //cy.wait(2000);
    cy.get('.offset-lg-1 > .row > :nth-child(5) > .ng-select > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
    cy.get('div:nth-of-type(2) > div:nth-of-type(37)').last().click();
    cy.get('#form_ > .mt-3 > .col-lg-12 > .btn-success').click();
    cy.get('.btn.btn-sm.btn-success.dropdown-toggle').click();
    cy.get('[class="btn-group btn-group1 flex-wrap mr-1 show"] [role] [class="dropdown-item text-1"]:nth-of-type(1)').click();
    cy.get('.btn.btn-sm.btn-success.dropdown-toggle').click();
    cy.get('[class="btn-group btn-group1 flex-wrap mr-1 show"] [role] [class="dropdown-item text-1"]:nth-of-type(3)').click();
    cy.get('.right-wrapper > .btn-default').click();
    cy.get('#ace > tbody > :nth-child(1) > :nth-child(12) > .btn-group > .mb-1 > .fas').first().click();
    cy.get('#ace > tbody > :nth-child(1) > :nth-child(12) > .btn-group > .dropdown-menu > button.dropdown-item').last().click();
    /* ==== End Cypress Studio ==== */
  });
  /* === Test Created with Cypress Studio === */
  it('validation error message Test', function () {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('http://localhost:4200/');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('e2etestcarrier');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('FleetHawks@2502');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(3) > .nav-link').click();
    cy.get(':nth-child(5) > .nav-link > span').click();
    cy.get('.page-header > .form-horizontal > .row > .text-right > .btn').click();
    cy.get('#form_ > .mt-3 > .col-lg-12 > .btn-success').click();
    /* ==== End Cypress Studio ==== */
  });


});
