/* === Test Created with Cypress Studio === */
it('add-order', function () {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit('https://devapp.fleethawks.com/');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('e2etestcarrier');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('FleetHawks@2502');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(3) > .nav-link').click();
    cy.get('.ng-star-inserted > .nav > :nth-child(1) > .nav-link').click();
    cy.get('.page-header > .form-horizontal > .row > .text-right > .btn').click();
    cy.get('.col-lg-10 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div[role="option"] > .ng-option-label.ng-star-inserted').last().click();
    cy.get(':nth-child(2) > .mt-2 > .col-lg-10 > .form-control').clear();
    cy.get(':nth-child(2) > .mt-2 > .col-lg-10 > .form-control').type('132589');
    cy.get(':nth-child(3) > :nth-child(2) > .col-lg-5 > .form-control').clear();
    cy.get(':nth-child(3) > :nth-child(2) > .col-lg-5 > .form-control').type('johnyy bravo');
    cy.get('.form-group.mt-3 > :nth-child(3) > :nth-child(3) > :nth-child(1) > .form-control').clear();
    cy.get('.form-group.mt-3 > :nth-child(3) > :nth-child(3) > :nth-child(1) > .form-control').type('1248566');
    cy.get(':nth-child(3) > :nth-child(3) > :nth-child(2) > .form-control').clear();
    cy.get(':nth-child(3) > :nth-child(3) > :nth-child(2) > .form-control').type('yahoo@gmail.com');
    cy.get(':nth-child(4) > .col-lg-10 > .form-control').clear();
    cy.get(':nth-child(4) > .col-lg-10 > .form-control').type('589622');
    cy.get('div#collapseShipperArea-0 > .row  ng-select[role="listbox"] input[role="combobox"]').first().click();
    cy.get('div[role="option"] > .ng-option-label.ng-star-inserted').last().click();
    cy.get('#collapseShipperArea-0 > :nth-child(2) > .col-lg-12 > .form-control').clear();
    cy.get('#collapseShipperArea-0 > :nth-child(2) > .col-lg-12 > .form-control').type('cal');
    cy.get('#collapseShipperArea-0 > :nth-child(2) > .col-lg-12 > .p-0 > :nth-child(1) > a').click();
    
    cy.get('#collapseShipperArea-0 > :nth-child(5) > .col-lg-12 > #inputDefault').type('Geroge smith');
    cy.get('#collapseShipperArea-0 > :nth-child(6) > .col-lg-12 > #inputDefault').clear();
    cy.get('#collapseShipperArea-0 > :nth-child(6) > .col-lg-12 > #inputDefault').type('1741398');
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(1) > .col-lg-10 > .form-control').clear();
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(1) > .col-lg-10 > .form-control').type('Nut bolts');
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(2) > .col-lg-12 > #inputDefault').clear();
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(2) > .col-lg-12 > #inputDefault').type('123692');
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(3) > :nth-child(2) > .form-control').clear();
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(3) > :nth-child(2) > .form-control').type('30');
    cy.get('div#collapseShipperArea-0 > .ng-star-inserted > div:nth-of-type(3)  ng-select[role="listbox"] input[role="combobox"]').first().click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(3)').last().click();

    
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(4) > :nth-child(2) > .form-control').type('2500');
    cy.get('#collapseShipperArea-0 > :nth-child(7) > :nth-child(4) > :nth-child(3) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').first().click();
  cy.get('[role="option"]:nth-of-type(2) .ng-star-inserted').last().click();
    cy.get('#collapseShipperArea-0 > :nth-child(8) > .col-lg-5 > .btn-group-toggle > :nth-child(1)').click();
    cy.get('.mb-1 > .btn').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(1) > .col-lg-11 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#af7495756d82-0').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(2) > .col-lg-12 > .form-control').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(2) > .col-lg-12 > .form-control').type('us');
    // cy.get('#collapseReceiverArea-0 > :nth-child(2) > .col-lg-12 > .p-0 > :nth-child(3) > a').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(3) > :nth-child(2) > .input-group > .form-control').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(3) > :nth-child(3) > .input-group > .timepicker').click();
    // cy.get('#static-0 > .card-body > .form-group').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(4) > .col-lg-12 > #textareaDefault').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(5) > .col-lg-12 > #inputDefault').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(5) > .col-lg-12 > #inputDefault').type('David Milan');
    // cy.get('#collapseReceiverArea-0 > :nth-child(6) > .col-lg-12 > #inputDefault').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(6) > .col-lg-12 > #inputDefault').type('774441100236');
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(1) > .col-lg-10 > .form-control').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(1) > .col-lg-10 > .form-control').type('cakes');
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(2) > .col-lg-12 > #inputDefault').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(2) > .col-lg-12 > #inputDefault').type('14589369');
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(3) > :nth-child(2) > .form-control').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(3) > :nth-child(2) > .form-control').type('23');
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(3) > :nth-child(3) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#a1594548cf31-0').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(4) > :nth-child(2) > .form-control').clear();
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(4) > :nth-child(2) > .form-control').type('1258');
    // cy.get('#collapseReceiverArea-0 > :nth-child(7) > :nth-child(4) > :nth-child(3) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#a7eba1311eaa-1').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(8) > .col-lg-5 > .btn-group-toggle > :nth-child(1)').click();
    // cy.get('#collapseReceiverArea-0 > :nth-child(8) > .col-lg-3 > :nth-child(1) > .btn').click();
    // cy.get('.col-lg-8 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#aaf76f71b31a-2').click();
    // cy.get(':nth-child(4) > .checkbox-custom > .control-label').click();
    // cy.get(':nth-child(5) > .col-lg-8 > .form-control').click();
    // cy.get('#google').click();
    // cy.get('.col-lg-8 > #textareaDefault').click();
    // cy.get(':nth-child(2) > .col-md-12 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#ad2231285a90-0').click();
    // cy.get(':nth-child(2) > :nth-child(3) > .input-group > .form-control').clear();
    // cy.get(':nth-child(2) > :nth-child(3) > .input-group > .form-control').type('57');
    // cy.get(':nth-child(2) > :nth-child(4) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#ae0fc6589592-0 > .ng-option-label').click();
    // cy.get(':nth-child(3) > .col-lg-3.offset-lg-2 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#abff4155e3fb-2').click();
    // cy.get(':nth-child(5) > :nth-child(2) > :nth-child(3) > :nth-child(3) > .input-group > .form-control').clear();
    // cy.get(':nth-child(5) > :nth-child(2) > :nth-child(3) > :nth-child(3) > .input-group > .form-control').type('477');
    // cy.get(':nth-child(4) > .col-lg-3 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#aff3f51fc5b2-0 > .ng-option-label').click();
    // cy.get(':nth-child(4) > :nth-child(3) > .input-group > .form-control').clear();
    // cy.get(':nth-child(4) > :nth-child(3) > .input-group > .form-control').type('19');
    // cy.get(':nth-child(5) > .col-lg-3 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    // cy.get('#a21d79838417-1 > .ng-option-label').click();
    // cy.get(':nth-child(5) > :nth-child(3) > .input-group > .form-control').clear();
    // cy.get(':nth-child(5) > :nth-child(3) > .input-group > .form-control').type('127');
    // cy.get(':nth-child(5) > .col-lg-5 > .form-control').clear();
    // cy.get(':nth-child(5) > .col-lg-5 > .form-control').type('350');
    // cy.get(':nth-child(6) > .col-lg-12 > .btn-success').click();
    // /* ==== End Cypress Studio ==== */
});