
it('added user with required optional fields ', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get('.content-body > .page-header > .row > .col-md-8 > .btn').click();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').type('new user');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(2) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(2) > .form-control').type('bookstore');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').type('test');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').type('smith');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').type('123456');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').type('2345678987');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(2) > .form-control').click();
    cy.get('.ngb-dp-today > .btn-light').click();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').type('newuser@mailinator.com');
    cy.get('.col-lg-5 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get(':nth-child(2) > :nth-child(2) > .row > .col-lg-4 > .form-control').clear();
    cy.get(':nth-child(2) > :nth-child(2) > .row > .col-lg-4 > .form-control').type('roc');
    cy.get('.p-0 > :nth-child(2) > a').click();
    cy.get('#userForm > :nth-child(3) > :nth-child(2) > .row > :nth-child(1) > .form-control').click();
    cy.get('.ngb-dp-today > .btn-light').click();
    cy.get('#userForm > :nth-child(3) > :nth-child(2) > .row > :nth-child(2) > .form-control').click();
    cy.get('[aria-label="Sunday, July 25, 2021"] > .btn-light').click();
    cy.get('#userForm > :nth-child(3) > .offset-lg-1 > .row > :nth-child(1) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('.offset-lg-1 > .row > :nth-child(2) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get('.col > .checkbox-custom > .ng-untouched').check();
    cy.get(':nth-child(5) > :nth-child(1) > .row > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(5) > :nth-child(1) > .row > :nth-child(1) > .form-control').type('newuser.123');
    cy.get(':nth-child(5) > :nth-child(1) > .row > :nth-child(2) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[role="option"]').click();
    cy.get(':nth-child(5) > .offset-lg-1 > .row > :nth-child(1)').click();
    cy.get('.offset-lg-1 > .row > :nth-child(1) > .input-group > #pd').click();
    cy.get('.offset-lg-1 > :nth-child(1) > :nth-child(1) > .input-group > #pd').clear();
    cy.get('.offset-lg-1 > :nth-child(1) > :nth-child(1) > .input-group > #pd').type('Hello#1');
    cy.get('.offset-lg-1 > .row > :nth-child(1) > .input-group > #pd').clear();
    cy.get('.offset-lg-1 > .row > :nth-child(1) > .input-group > #pd').type('Hello#123');
    cy.get('.offset-lg-1 > .row > :nth-child(2) > .input-group > #cnf').clear();
    cy.get('.offset-lg-1 > .row > :nth-child(2) > .input-group > #cnf').type('Hello#123');
    cy.get(':nth-child(6) > :nth-child(2) > .row > .col-lg-6 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get(':nth-child(6) > :nth-child(2) > .row > :nth-child(2) > .form-control').clear();
    cy.get(':nth-child(6) > :nth-child(2) > .row > :nth-child(2) > .form-control').type('12');
    cy.get(':nth-child(6) > :nth-child(2) > .row > :nth-child(3) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get(':nth-child(6) > .offset-lg-1 > .row > :nth-child(1) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get(':nth-child(6) > .offset-lg-1 > .row > :nth-child(2) > .form-control').clear();
    cy.get(':nth-child(6) > .offset-lg-1 > .row > :nth-child(2) > .form-control').type('123456765');
    cy.get(':nth-child(6) > :nth-child(2) > .row > .col-lg-12 > .form-control').clear();
    cy.get(':nth-child(6) > :nth-child(2) > .row > .col-lg-12 > .form-control').type('34567');
    cy.get(':nth-child(6) > .offset-lg-1 > .row > .col-lg-12 > .form-control').clear();
    cy.get(':nth-child(6) > .offset-lg-1 > .row > .col-lg-12 > .form-control').type('123456');
    //   cy.get(':nth-child(6) > .text-right > .btn-success').click();
    cy.get('[class="col-lg-11 text-right mt-3"] [data-dismiss]').click();
    cy.wait(6000);
});


it('added user with required  fields and button should be enable', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get('.content-body > .page-header > .row > .col-md-8 > .btn').click();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').type('new required user');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').type('78909');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').type('Elina');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').type('smith');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').type('6547891234');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').type('newrequired@mailinator.com');
    cy.get('.col > .checkbox-custom > .ng-untouched').check();
    cy.get(':nth-child(5) > :nth-child(1) > .row > :nth-child(1) > .form-control').clear();
    cy.get(':nth-child(5) > :nth-child(1) > .row > :nth-child(1) > .form-control').type('requireduser.123');
    cy.get(':nth-child(5) > :nth-child(1) > .row > :nth-child(2) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('[role="option"]').click();
    cy.get(':nth-child(5) > .offset-lg-1 > .row > :nth-child(1)').click();
    cy.get('.offset-lg-1 > .row > :nth-child(1) > .input-group > #pd').click();
    cy.get('.offset-lg-1 > :nth-child(1) > :nth-child(1) > .input-group > #pd').clear();
    cy.get('.offset-lg-1 > :nth-child(1) > :nth-child(1) > .input-group > #pd').type('Hello#1');
    cy.get('.offset-lg-1 > .row > :nth-child(1) > .input-group > #pd').clear();
    cy.get('.offset-lg-1 > .row > :nth-child(1) > .input-group > #pd').type('Hello#123');
    cy.get('.offset-lg-1 > .row > :nth-child(2) > .input-group > #cnf').clear();
    cy.get('.offset-lg-1 > .row > :nth-child(2) > .input-group > #cnf').type('Hello#123');
    cy.get(':nth-child(6) > :nth-child(2) > .row > .col-lg-6 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get(':nth-child(6) > .offset-lg-1 > .row > :nth-child(2) > .form-control').clear();
    cy.get(':nth-child(6) > .offset-lg-1 > .row > :nth-child(2) > .form-control').type('777777777');
    //   cy.get(':nth-child(6) > .text-right > .btn-success').click();
    cy.get('[class="col-lg-11 text-right mt-3"] [data-dismiss]').click();
    cy.wait(6000);
});

it('user should be able to edit', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get(':nth-child(1) > :nth-child(8) > .btn-group > .mb-1 > .fas').click();
    cy.get(':nth-child(1) > :nth-child(8) > .btn-group > .dropdown-menu > a.dropdown-item').click();
    cy.wait(8000);
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').type('8888');
    // cy.get(':nth-child(6) > .text-right > .btn-success').click();
    cy.get('[class="col-lg-11 text-right mt-3"] [data-dismiss]').click();
    cy.wait(6000);

});

it('user should be able to delete', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get('.pr-0 > .input-group > .form-control').click();
    cy.get('.pr-0 > .input-group > .form-control').type('marion');
    cy.get('.result-suggestions > ul').click();
    cy.get('.pl-2 > .mr-2').click();
    cy.wait(8000);
});

it('user should be able to search', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get('.pr-0 > .input-group > .form-control').click();
    cy.get('.pr-0 > .input-group > .form-control').type('test');
    cy.get('.result-suggestions > ul > :nth-child(2)').click();
    cy.get('.pl-2 > .mr-2').click();
    cy.wait(8000);
    cy.get('.pl-2 > [type="button"]').click();
    cy.wait(8000);
});

it('button disable with optional fields and user should not able to add the form ', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get('.content-body > .page-header > .row > .col-md-8 > .btn').click();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(2) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(2) > .form-control').type('bookstore');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(2) > .form-control').click();
    cy.get('.ngb-dp-today > .btn-light').click();
    cy.get('.col-lg-5 > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get(':nth-child(2) > :nth-child(2) > .row > .col-lg-4 > .form-control').clear();
    cy.get(':nth-child(2) > :nth-child(2) > .row > .col-lg-4 > .form-control').type('roc');
    cy.get('.p-0 > :nth-child(2) > a').click();
    cy.get('#userForm > :nth-child(3) > :nth-child(2) > .row > :nth-child(1) > .form-control').click();
    cy.get('.ngb-dp-today > .btn-light').click();
    cy.get('#userForm > :nth-child(3) > :nth-child(2) > .row > :nth-child(2) > .form-control').click();
    cy.get('[aria-label="Sunday, July 25, 2021"] > .btn-light').click();
    cy.get('#userForm > :nth-child(3) > .offset-lg-1 > .row > :nth-child(1) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('.offset-lg-1 > .row > :nth-child(2) > .form-control > .ng-select-container > .ng-value-container > .ng-input > input').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(2)').click();
    cy.get(':nth-child(5) > :nth-child(2) > .row > :nth-child(2) > .form-control').clear();
    cy.get(':nth-child(5) > :nth-child(2) > .row > :nth-child(2) > .form-control').type('12');
    cy.get(':nth-child(5) > :nth-child(2) > .row > :nth-child(3) > .form-control > .ng-select-container').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get(':nth-child(5) > .offset-lg-1 > .row > :nth-child(1) > .form-control > .ng-select-container').click();
    cy.get('div:nth-of-type(2) [role="option"]:nth-of-type(1)').click();
    cy.get('#userForm > :nth-child(5) > :nth-child(2) > .row > .col-lg-12 > .form-control').clear();
    cy.get('#userForm > :nth-child(5) > :nth-child(2) > .row > .col-lg-12 > .form-control').type('34567');
    cy.get(':nth-child(5) > .offset-lg-1 > .row > .col-lg-12 > .form-control').clear();
    cy.get(':nth-child(5) > .offset-lg-1 > .row > .col-lg-12 > .form-control').type('123456');
    cy.wait(8000);
});

it.only('validation error on required fields ', function () {
    cy.visit('/#/Login');
    cy.get(':nth-child(1) > .input-group > .form-control').clear();
    cy.get(':nth-child(1) > .input-group > .form-control').type('rashmi.cypress123');
    cy.get(':nth-child(2) > .input-group > .form-control').clear();
    cy.get(':nth-child(2) > .input-group > .form-control').type('Hello#123');
    cy.get('#btnsubmit').click();
    cy.get('nav > .nav > :nth-child(6) > .nav-link').click();
    cy.get(':nth-child(4) > .nav-link > span').click();
    cy.get('.content-body > .page-header > .row > .col-md-8 > .btn').click();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').type('new required user');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(1) > .form-control').clear();
    cy.get('[name] [class="row pt-3"]:nth-of-type(1) .ng-star-inserted .ng-star-inserted').contains('Company name is required');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').type('78909');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(1) > .form-control').clear();
    cy.get('.col-lg-5.offset-lg-1 .ng-star-inserted').contains('Employee ID is required.');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').type('Elina');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(3) > .form-control').clear();
    cy.get('div:nth-of-type(3) > .ng-star-inserted.text-danger > .ng-star-inserted').contains('First name is required');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').type('smith');
    cy.get('#userForm > :nth-child(1) > :nth-child(2) > .row > :nth-child(4) > .form-control').clear();
    cy.get('div:nth-of-type(4) > .ng-star-inserted.text-danger > .ng-star-inserted').contains('Last name is required.');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').type('6547891234');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(3) > .form-control').clear();
    cy.get('.col-lg-5.offset-lg-1 > div > div:nth-of-type(3) > .ng-star-inserted.text-danger > .ng-star-inserted').contains('Phone is required');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').clear();
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').type('newrequired@mailinator.com');
    cy.get('#userForm > :nth-child(1) > .offset-lg-1 > .row > :nth-child(4) > .form-control').clear();
    cy.get('.col-lg-5.offset-lg-1 > div > div:nth-of-type(4) > .ng-star-inserted.text-danger > .ng-star-inserted').contains('Email is required');
    cy.get(':nth-child(5) > .text-right > .btn-default').click();
});