on: [pull_request]
name: Build Angular App
jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Get NodeJs 14.x and Cache
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          cache: 'npm'
      - name: Install dev dependencies and build
        run: |
          npm install
          export NODE_OPTIONS="--max-old-space-size=16000"
          npm run buildDev
