 name: Pre-Merge E2E tests
 on: [push]
 jobs:
   cypress-run:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node: [12]
     timeout-minutes: 15
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       
       - name: Cypress run
         uses: cypress-io/github-action@v2
         
